package com.example.lab8.Languagesss;

import java.util.ListResourceBundle;

public class StatsBundle_be_esp extends ListResourceBundle {
    @Override
    public Object[][] getContents() {
        return contents;
    }
    private final Object[][] contents = {
            //{ "LOG IN", "Дапамога" },
            //{ "SIGN UP", "Інфармацыя" },
            { "Username", "Nombre de usuario" },
            { "Password", "Contraseña" },
            { "Languages", "Selección de idioma" },
            { "SIGN IN", "Iniciar sesión" },
            { "regist", "registro" },
            { "Info", "Información" },
            { "Clear", "Limpiar" },
            { "Help", "Ayuda" },
            { "Remove", "Eliminar" },
            { "Add", "Agregar" },
            { "Print", "Imprimir" },
            { "PrintType", "salida por tipo" },
            { "PrintAge", "conclusión por edad" },
            { "LogOut", "Cerrar sesión" },
            { "Save", "Guardar" },
            { "Exit", "Salir" },
            { "Map", "Mapa" },
            { "fieldInfo", "Campo de información" },
            { "name", "nombre" },
            { "id", "id" },
            { "x", "x" },
            { "y", "y" },
            {"color", "Color"},
            {"weight", "Peso"},
            { "age", "Edad" },
            { "type", "Tipo" },
            { "size", "Tamaño" },
            { "eyes", "Ojos" },
            { "tooth", "Dientes" },
            { "data", "Fecha" },
            { "type", "tipo" },
            { "addh", "add: Comando para agregar un nuevo elemento a la colección" },
            { "helph", "help: Comando para mostrar ayuda sobre los comandos disponibles" },
            { "exith", "exit: Comando para salir del programa" },
            { "logouth", "logout: Comando para cerrar sesión" },
            { "print_ageh", "print_age: Comando para imprimir los valores del campo age de todos los elementos en orden ascendente" },
            { "add_if_minh", "add_if_min: Comando para agregar un nuevo elemento a la colección si su valor es menor que el valor mínimo en la colección" },
            { "clearh", "clear: Comando para limpiar la colección" },
            { "print_typeh", "print_type: Comando para imprimir los valores del campo type de todos los elementos en orden descendente" },
            { "infoh", "info: Comando para mostrar información sobre la colección en la salida estándar" },
            { "update_idh", "update_id: Comando para actualizar el valor de un elemento en la colección cuyo id coincide con el especificado"},
            {"remove_by_idh", "remove_by_id: Elimina un elemento de la colección según su id"},
            //{"remove_by_indexh", "eliminar elementos por índice"},
            {"remove_greaterh", "remove_greater: Comando para eliminar de la colección todos los elementos que sean mayores que un elemento dado. Funciona según el campo size"},
            {"remove_by_typeh", "remove_by_type: Comando para eliminar un elemento de la colección donde el valor del campo type es igual al valor especificado"},
            {"removeIdB", "Eliminar por ID"},
            {"RemoveTypeB", "Eliminar por tipo"},
            {"remomeGreatB", "Eliminar mayores"},
            {"fieldId", "Campo para ingresar ID"},
            {"fieldType", "Campo para ingresar tipo"},
            {"fieldSize", "Campo para ingresar tamaño"},
            {"nameA", "Nombre"},
            {"ageA", "Edad"},
            {"weightA", "Peso"},
            {"colorA", "Color"},
            {"typeA", "Tipo"},
            {"toothA", "Dientes"},
            {"eyesA", "Ojos"},
            {"sizeA", "Tamaño"},
            {"xA", "Coordenadas X"},
            {"yA", "Coordenadas Y"},
            {"yellow", "Amarillo"},
            {"orange", "Naranja"},
            {"white", "Blanco"},
            {"air", "Aire"},
            {"water", "Agua"},
            {"underground", "Subterráneo"},

            {"addA", "Agregar"},
            {"addminA", "Agregar si es mínimo"},
            {"updateIdA", "Actualizar por ID"},
            {"fieldIdA", "Ingrese ID"},
            {"notPasswd", "Las contraseñas ingresadas no coinciden"},
            {"LoginErr", "Error al iniciar sesión"},
            {"error", "Error"},
            {"wrongPasswd", "Contraseña incorrecta. Intentos restantes: "},
            {"isColl", "La colección está vacía, el comando no tiene sentido"},
            {"notDelete", "No se ha eliminado ningún dragón"},
            {"notUser", "El objeto pertenece a otro usuario"},
            {"notExistId", "El ID ingresado no existe"},
            {"succ", "con éxito"},
            {"changeObj", "El objeto ha sido modificado"},
            {"addMin", "El valor del elemento más pequeño en la colección es menor"},
            {"not1delete", "No se ha eliminado ningún dragón"},
            {"notAcc", "No existe una cuenta con ese nombre de usuario"},
            {"yetExist", "Ya existe una cuenta con ese nombre de usuario"},
            {"succReg", "Registro de cuenta exitoso"},
            {"errArg", "Error de argumento"},
            {"argForm", "El formato del argumento no coincide"},
            {"notExistType", "No existe ese tipo"},
            {"needNumber", "Se requiere ingresar un número para que el comando funcione"},
            {"argComm", "Faltan argumentos del comando"},
            {"necorrName", "Valor ingresado incorrecto"}

    };
}
