package com.example.lab8.Languagesss;

import java.util.ListResourceBundle;

public class StatsBundle_be_sl extends ListResourceBundle {
    @Override
    public Object[][] getContents() {
        return contents;
    }
    private final Object[][] contents = {
            //{ "LOG IN", "Дапамога" },
            //{ "SIGN UP", "Інфармацыя" },
            { "Username", "Meno používateľa" },
            { "Password", "Heslo" },
            { "Languages", "Výber jazyka" },
            { "SIGN IN", "Prihlásiť sa" },
            { "regist", "registrácia" },
            { "Info", "Info" },
            { "Clear", "Vyčistiť" },
            { "Help", "Pomoc" },
            { "Remove", "Odstrániť" },
            { "Add", "Pridať" },
            { "Print", "Výpis" },
            { "PrintType", "výstup podľa typu" },
            { "PrintAge", "záver podľa veku" },
            { "LogOut", "Odhlásiť sa" },
            { "Save", "Uložiť" },
            { "Exit", "Ukončiť" },
            { "Map", "Mapa" },
            { "fieldInfo", "Pole pre výstup informácií" },
            { "name", "meno" },
            { "id", "id" },
            { "x", "x" },
            { "y", "y" },
            {"color", "Farba"},
            {"weight", "Váha"},
            { "age", "Vek" },
            { "type", "Typ" },
            { "size", "Veľkosť" },
            { "eyes", "Oči" },
            { "tooth", "Zuby" },
            { "data", "Dátum" },
            { "type", "typ" },
            { "addh", "add: Príkaz pridáva nový prvok do kolekcie" },
            { "helph", "help: Príkaz zobrazuje nápovedu k dostupným príkazom" },
            { "exith", "exit: Príkaz ukončuje program" },
            { "logouth", "logout: Príkaz umožňuje odhlásiť sa" },
            { "print_ageh", "print_age: Príkaz zobrazuje hodnoty poľa age všetkých prvkov v poradí vzostupne" },
            { "add_if_minh", "add_if_min: Príkaz pridáva nový prvok do kolekcie, ak je jeho hodnota menšia ako najmenší prvok tejto kolekcie" },
            { "clearh", "clear: Príkaz vyprázdňuje kolekciu" },
            { "print_typeh", "print_type: Príkaz zobrazuje hodnoty poľa type všetkých prvkov v poradí zostupne" },
            { "infoh", "info: Príkaz zobrazuje informácie o kolekcii v štandardnom výstupnom prúde" },
            { "update_idh", "update_id: Príkaz aktualizuje hodnotu prvku kolekcie, ktorého id je rovnaké ako zadané"},
            {"remove_by_idh", "remove_by_id: Odstráni prvok z kolekcie podľa jeho id"},
            //{"remove_by_indexh", "vymazať prvky podľa indexov"},
            {"remove_greaterh", "remove_greater: Príkaz odstraňuje zo zbierky všetky prvky väčšie ako zadaný. Pracuje podľ a veľkosti"},
                    {"remove_by_typeh", "remove_by_type: Príkaz odstraňuje zo zbierky jeden prvok, ktorého hodnota poľa type je ekvivalentná so zadaným"},
                    {"removeIdB", "Odstrániť podľa ID"},
                    {"RemoveTypeB", "Odstrániť podľa typu"},
                    {"remomeGreatB", "Odstrániť väčší"},
                    {"fieldId", "Pole pre zadanie ID"},
                    {"fieldType", "Pole pre zadanie typu"},
                    {"fieldSize", "Pole pre zadanie veľkosti"},
                    {"nameA", "Meno"},
                    {"ageA", "Vek"},
                    {"weightA", "Váha"},
                    {"colorA", "Farba"},
                    {"typeA", "Typ"},
                    {"toothA", "Zuby"},
                    {"eyesA", "Oči"},
                    {"sizeA", "Veľkosť"},
            {"xA", "Koordinovať X"},
            {"yA", "Koordinovať Y"},
            {"yellow", "Žltá"},
            {"orange", "Oranžová"},
            {"white", "Biela"},
            {"air", "Vzduch"},
            {"water", "Voda"},
            {"underground", "Podzemie"},
                    {"addA", "Pridať"},
                    {"addminA", "Pridať ak min"},
                    {"updateIdA", "Aktualizovať podľa ID"},
                    {"fieldIdA", "Zadajte ID"},
            {"notPasswd", "Zadané heslá sa nezhodujú"},
            {"LoginErr", "Chyba pri prihlasovaní"},
            {"error", "Chyba"},
            {"wrongPasswd", "Nesprávne heslo. Zostávajúce pokusy: "},
            {"isColl", "Kolekcia je prázdna, príkaz nemá význam"},
            {"notDelete", "Žiadny drak nebol odstránený"},
            {"notUser", "Objekt patrí inému používateľovi"},
            {"notExistId", "Zadané ID neexistuje"},
            {"changeObj", "Objekt bol zmenený"},
            {"addMin", "U najmenšieho prvku v kolekcii je hodnota menšia"},
            {"not1delete", "Žiadny drak nebol odstránený"},
            {"notAcc", "Neexistuje účet s týmto prihlasovacím menom"},
            {"yetExist", "Účet s týmto prihlasovacím menom už existuje"},
            {"succReg", "Registrácia účtu bola úspešná"},
            {"errArg", "Chyba s argumentom"},
            {"argForm", "Formát argumentu nezodpovedá"},
            {"notExistType", "Neexistuje takýto typ"},
            {"needNumber", "Pre správne fungovanie príkazu je potrebné zadať číslo"},
            {"argComm", "Chýbajú argumenty príkazu"},
            {"necorrName", "Zadaná neplatná hodnota"}
    };
}

